[package]
name = "inference-server"
version = "0.1.0"
edition = "2021"

[dependencies]
# workspace dependencies
inference-protocol = { path = "../inference-protocol", version = "0.1" }

# creates.io dependencies
tonic = { version = "0.8", default-features = false, features = [
  "transport",
  "codegen",
  "prost",
] }
bytes = { version = "1", default-features = false }
prost = { version = "0.11", default-features = false }
