apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "inference-server.fullname" . }}-envoy
  labels:
    app: {{ template "inference-server.name" . }}
    chart: {{ template "inference-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  envoy.yaml: |
    {{- .Files.Get "files/envoy.yaml" | nindent 4 }}
