apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inference-server.fullname" . }}
  labels:
    {{- include "inference-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "inference-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "inference-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "inference-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: envoy
          image: "{{ .Values.envoy.image.repository }}:{{ .Values.envoy.image.tag }}"
          imagePullPolicy: {{ .Values.envoy.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: envoy-config
              mountPath: /opt/bitnami/envoy/conf/envoy.yaml
              subPath: envoy.yaml
              readOnly: true
          resources:
            {{- toYaml .Values.envoy.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.envoy.securityContext | nindent 12 }}
        - name: inference
          image: "{{ .Values.inference.image.repository }}:{{ .Values.inference.image.tag }}"
          imagePullPolicy: {{ .Values.inference.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.inference.containerPort }}
              protocol: TCP
          volumeMounts:
            - name: inference-config
              mountPath: /opt/app/repo.yaml
              subPath: repo.yaml
              readOnly: true
          livenessProbe:
            grpc:
              port: {{ .Values.inference.containerPort }}
            initialDelaySeconds: 3
          readinessProbe:
            grpc:
              port: {{ .Values.inference.containerPort }}
          resources:
            {{- toYaml .Values.inference.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.inference.securityContext | nindent 12 }}
        - name: mlflow
          image: "{{ .Values.mlflow.image.repository }}:{{ .Values.mlflow.image.tag }}"
          imagePullPolicy: {{ .Values.mlflow.image.pullPolicy }}
          command: ["mlflow"]
          args:
            - server
            - --host=0.0.0.0
            - --port={{ .Values.mlflow.containerPort }}
          ports:
            - name: http-mlflow
              containerPort: {{ .Values.mlflow.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.mlflow.containerPort }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.mlflow.containerPort }}
          resources:
            {{- toYaml .Values.mlflow.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.mlflow.securityContext | nindent 12 }}
      volumes:
        - name: envoy-config
          configMap:
            name: {{ template "inference-server.fullname" . }}-envoy
        - name: inference-config
          configMap:
            name: {{ template "inference-server.fullname" . }}-inference
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
